/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class rijndaelJNI {
  public final static native String enc(String jarg1, String jarg2);
  public final static native String dec(String jarg1, String jarg2);
}
