/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class rijndael {
  public static String enc(String password, String filename) {
    return rijndaelJNI.enc(password, filename);
  }

  public static String dec(String password, String filename) {
    return rijndaelJNI.dec(password, filename);
  }

}
