python: 
	cd python_wrap && make

perl:
	cd perl_wrap && make

csharp:
	cd csharp_wrap && make

java:
	cd java_wrap && make

.PNONY: clean

clean:
	cd python_wrap && make clean
	cd perl_wrap && make clean
	cd csharp_wrap && make clean
	cd java_wrap && make clean
